env:
  node: true
  commonjs: true
  es2021: true
extends: eslint:recommended
overrides:
  - files: "*.js"
    rules:
      "no-unused-vars": ["error", { "argsIgnorePattern": "next" }]
  - files: "*.test.js"
    rules:
      "no-unused-vars": "off"
parserOptions:
  ecmaVersion: latest
